#import "../config.typ": *

#h1(offset: whole,
  if lang == "en" [Design Contracts]
  else if lang == "de" [Design-Verträge]
  else { todo })
#set heading(offset: whole*2)

#if lang == "en" [
  In our last chapter, we wrote an interface that _didn't_ enforce
  design contracts. Let's take another look at our imaginary GPIO
  configuration register:
] else if lang == "de" [
  Im letzten Kapitel haben wir eine Schnittstelle geschrieben, die
  _keine_ Design-Verträge (Design Contracts) durchsetzte. Werfen wir
  noch einmal einen Blick auf unser fiktives GPIO-Konfigurationsregister:
] else { todo }

#include "gpio-table.typ"

#if lang == "en" [
  If we instead checked the state before making use of the underlying
  hardware, enforcing our design contracts at runtime, we might write code
  that looks like this instead:
] else if lang == "de" [
  Wenn wir stattdessen den Zustand überprüfen würden, bevor wir die
  zugrundeliegende Hardware nutzen, und dabei unsere Entwurfsverträge zur
  Laufzeit durchsetzen würden, könnten wir stattdessen Code schreiben, der
  wie folgt aussieht:
] else { todo }

#raw(block: true, lang: "rust",
"/// " + if lang == "en" {
    "GPIO interface"
  } else if lang == "de" {
    "GPIO-Schnittstelle"
  } else { todos } + "
struct GpioConfig {
    /// " + if lang == "en" {
        "GPIO Configuration structure generated by svd2rust"
      } else if lang == "de" {
        "Von svd2rust generierte GPIO-Konfigurationsstruktur"
      } else { todos } + "
    periph: GPIO_CONFIG,
}

impl GpioConfig {
    pub fn set_enable(&mut self, is_enabled: bool) {
        self.periph.modify(|_r, w| {
            w.enable().set_bit(is_enabled)
        });
    }

    pub fn set_direction(&mut self, is_output: bool) -> Result<(), ()> {
        if self.periph.read().enable().bit_is_clear() {
            // " + if lang == "en" {
                "Must be enabled to set direction"
              } else if lang == "de" {
                "Muss aktiviert sein, um die Richtung festzulegen."
              } else { todos } + "
            return Err(());
        }

        self.periph.modify(|r, w| {
            w.direction().set_bit(is_output)
        });

        Ok(())
    }

    pub fn set_input_mode(&mut self, variant: InputMode) -> Result<(), ()> {
        if self.periph.read().enable().bit_is_clear() {
            // " + if lang == "en" {
                "Must be enabled to set input mode"
              } else if lang == "de" {
                "Muss aktiviert sein, um den Eingabemodus festzulegen."
              } else { todos } + "
            return Err(());
        }

        if self.periph.read().direction().bit_is_set() {
            // " + if lang == "en" {
                "Direction must be input"
              } else if lang == "de" {
                "Die Richtung muss input sein."
              } else { todos } + "
            return Err(());
        }

        self.periph.modify(|_r, w| {
            w.input_mode().variant(variant)
        });

        Ok(())
    }

    pub fn set_output_status(&mut self, is_high: bool) -> Result<(), ()> {
        if self.periph.read().enable().bit_is_clear() {
            // " + if lang == "en" {
                "Must be enabled to set output status"
              } else if lang == "de" {
                "Muss aktiviert sein, um den Ausgangsstatus festzulegen."
              } else { todos } + "
            return Err(());
        }

        if self.periph.read().direction().bit_is_clear() {
            // " + if lang == "en" {
                "Direction must be output"
              } else if lang == "de" {
                "Die Richtung muss output sein."
              } else { todos } + "
            return Err(());
        }

        self.periph.modify(|_r, w| {
            w.output_mode.set_bit(is_high)
        });

        Ok(())
    }

    pub fn get_input_status(&self) -> Result<bool, ()> {
        if self.periph.read().enable().bit_is_clear() {
            // " + if lang == "en" {
                "Must be enabled to get status"
              } else if lang == "de" {
                "Muss aktiviert sein, um den Status abzurufen."
              } else { todos } + "
            return Err(());
        }

        if self.periph.read().direction().bit_is_set() {
            // " + if lang == "en" {
                "Direction must be input"
              } else if lang == "de" {
                "Die Richtung muss input sein."
              } else { todos } + "
            return Err(());
        }

        Ok(self.periph.read().input_status().bit_is_set())
    }
}
")

#if lang == "en" [
  Because we need to enforce the restrictions on the hardware, we end up
  doing a lot of runtime checking which wastes time and resources, and
  this code will be much less pleasant for the developer to use.
] else if lang == "de" [
  Da wir die Hardware-Beschränkungen durchsetzen müssen, führen wir
  letztlich zahlreiche Laufzeitüberprüfungen durch -- was Zeit und
  Ressourcen verschwendet --, und der Code ist für Entwickler deutlich
  weniger angenehm zu handhaben.
] else { todo }

= #(if lang == "en" [Type States]
  else if lang == "de" [Typzustände]
  else { todo })

#if lang == "en" [
  But what if instead, we used Rust's type system to enforce the state
  transition rules? Take this example:
] else if lang == "de" [
  Was aber, wenn wir stattdessen das Typsystem von Rust nutzen würden, um
  die Regeln für Zustandsübergänge durchzusetzen? Betrachten wir dieses
  Beispiel:
] else { todo }

#raw(block: true, lang: "rust",
"/// " + if lang == "en" {
    "GPIO interface"
  } else if lang == "de" {
    "GPIO-Schnittstelle"
  } else { todos } + "
struct GpioConfig<ENABLED, DIRECTION, MODE> {
    /// " + if lang == "en" {
        "GPIO Configuration structure generated by svd2rust"
      } else if lang == "de" {
        "Von svd2rust generierte GPIO-Konfigurationsstruktur"
      } else { todos } + "
    periph: GPIO_CONFIG,
    enabled: ENABLED,
    direction: DIRECTION,
    mode: MODE,
}

// " + if lang == "en" {
    "Type states for MODE in GpioConfig"
  } else if lang == "de" {
    "Typzustaende fuer MODE in GpioConfig"
  } else { todos } + "
struct Disabled;
struct Enabled;
struct Output;
struct Input;
struct PulledLow;
struct PulledHigh;
struct HighZ;
struct DontCare;

/// " + if lang == "en" {
    "These functions may be used on any GPIO Pin"
  } else if lang == "de" {
    "Diese Funktionen koennen an jedem GPIO-Pin verwendet werden."
  } else { todos } + "
impl<EN, DIR, IN_MODE> GpioConfig<EN, DIR, IN_MODE> {
    pub fn into_disabled(self) -> GpioConfig<Disabled, DontCare, DontCare> {
        self.periph.modify(|_r, w| w.enable.disabled());
        GpioConfig {
            periph: self.periph,
            enabled: Disabled,
            direction: DontCare,
            mode: DontCare,
        }
    }

    pub fn into_enabled_input(self) -> GpioConfig<Enabled, Input, HighZ> {
        self.periph.modify(|_r, w| {
            w.enable.enabled()
             .direction.input()
             .input_mode.high_z()
        });
        GpioConfig {
            periph: self.periph,
            enabled: Enabled,
            direction: Input,
            mode: HighZ,
        }
    }

    pub fn into_enabled_output(self) -> GpioConfig<Enabled, Output, DontCare> {
        self.periph.modify(|_r, w| {
            w.enable.enabled()
             .direction.output()
             .input_mode.set_high()
        });
        GpioConfig {
            periph: self.periph,
            enabled: Enabled,
            direction: Output,
            mode: DontCare,
        }
    }
}

/// " + if lang == "en" {
    "This function may be used on an Output Pin"
  } else if lang == "de" {
    "Diese Funktion kann fuer einen Ausgangspin verwendet werden."
  } else { todos } + "
impl GpioConfig<Enabled, Output, DontCare> {
    pub fn set_bit(&mut self, set_high: bool) {
        self.periph.modify(|_r, w| w.output_mode.set_bit(set_high));
    }
}

/// " + if lang == "en" {
    "These methods may be used on any enabled input GPIO"
  } else if lang == "de" {
    "Diese Methoden koennen auf jedem aktivierten Eingangs-GPIO verwendet werden."
  } else { todos } + "
impl<IN_MODE> GpioConfig<Enabled, Input, IN_MODE> {
    pub fn bit_is_set(&self) -> bool {
        self.periph.read().input_status.bit_is_set()
    }

    pub fn into_input_high_z(self) -> GpioConfig<Enabled, Input, HighZ> {
        self.periph.modify(|_r, w| w.input_mode().high_z());
        GpioConfig {
            periph: self.periph,
            enabled: Enabled,
            direction: Input,
            mode: HighZ,
        }
    }

    pub fn into_input_pull_down(self) -> GpioConfig<Enabled, Input, PulledLow> {
        self.periph.modify(|_r, w| w.input_mode().pull_low());
        GpioConfig {
            periph: self.periph,
            enabled: Enabled,
            direction: Input,
            mode: PulledLow,
        }
    }

    pub fn into_input_pull_up(self) -> GpioConfig<Enabled, Input, PulledHigh> {
        self.periph.modify(|_r, w| w.input_mode().pull_high());
        GpioConfig {
            periph: self.periph,
            enabled: Enabled,
            direction: Input,
            mode: PulledHigh,
        }
    }
}
")

#if lang == "en" [
  Now let's see what the code using this would look like:
] else if lang == "de" [
  Schauen wir uns nun an, wie der Code aussehen würde, der dies verwendet:
] else { todo }

#raw(block: true, lang: "rust",
"/*
 * " + if lang == "en" {
    "Example 1: Unconfigured to High-Z input"
  } else if lang == "de" {
    "Beispiel 1: Nicht konfiguriert als High-Z-Eingang"
  } else { todos } + "
 */
let pin: GpioConfig<Disabled, _, _> = get_gpio();

// " + if lang == "en" {
    "Can't do this, pin isn't enabled!"
  } else if lang == "de" {
    "Das ist nicht moeglich, die PIN ist nicht aktiviert!"
  } else { todos } + "
// pin.into_input_pull_down();

// " + if lang == "en" {
    "Now turn the pin from unconfigured to a high-z input"
  } else if lang == "de" {
    "Schalten Sie den Pin nun von „unkonfiguriert“ auf einen hochohmigen Eingang 
  // (High-Z-Eingang) um."
  } else { todos } + "
let input_pin = pin.into_enabled_input();

// " + if lang == "en" {
    "Read from the pin"
  } else if lang == "de" {
    "Vom Pin lesen"
  } else { todos } + "
let pin_state = input_pin.bit_is_set();

// " + if lang == "en" {
    "Can't do this, input pins don't have this interface!"
  } else if lang == "de" {
    "Das ist nicht moeglich; Eingangs-Pins verfuegen nicht über diese 
  // Schnittstelle!"
  } else { todos } + "
// input_pin.set_bit(true);

/*
 * " + if lang == "en" {
    "Example 2: High-Z input to Pulled Low input"
  } else if lang == "de" {
    "Beispiel 2: Hochohmiger Eingang (High-Z) an auf Low-Pegel gezogenen Eingang"
  } else { todos } + "
 */
let pulled_low = input_pin.into_input_pull_down();
let pin_state = pulled_low.bit_is_set();

/*
 * " + if lang == "en" {
    "Example 3: Pulled Low input to Output, set high"
  } else if lang == "de" {
    "Beispiel 3: Eingang auf Low gezogen, Ausgang auf High gesetzt"
  } else { todos } + "
 */
let output_pin = pulled_low.into_enabled_output();
output_pin.set_bit(true);

// " + if lang == "en" {
    "Can't do this, output pins don't have this interface!"
  } else if lang == "de" {
    "Das geht nicht, Ausgangspins verfuegen nicht über diese Schnittstelle!"
  } else { todos } + "
// output_pin.into_input_pull_down();
")

#if lang == "en" [
  This is definitely a convenient way to store the state of the pin, but
  why do it this way? Why is this better than storing the state as an
  `enum` inside of our `GpioConfig` structure?
] else if lang == "de" [
  Dies ist zweifellos eine praktische Möglichkeit, den Zustand des Pins zu
  speichern, aber warum sollte man es auf diese Weise tun? Warum ist das
  besser, als den Zustand als `enum` innerhalb unserer
  `GpioConfig`-Struktur zu speichern?
] else { todo }

= #(if lang == "en" [Compile Time Functional Safety]
  else if lang == "de" [Funktionale Sicherheit zur Kompilierzeit]
  else { todo })

#if lang == "en" [
  Because we are enforcing our design constraints entirely at compile
  time, this incurs no runtime cost. It is impossible to set an output
  mode when you have a pin in an input mode. Instead, you must walk
  through the states by converting it to an output pin, and then setting
  the output mode. Because of this, there is no runtime penalty due to
  checking the current state before executing a function.
] else if lang == "de" [
  Da wir unsere Designvorgaben vollständig zur Kompilierzeit durchsetzen,
  entstehen keinerlei Laufzeitkosten. Es ist unmöglich, einen Ausgabemodus
  einzustellen, solange sich ein Pin im Eingabemodus befindet. Stattdessen
  muss man die Zustände durchlaufen, indem man den Pin zunächst in einen
  Ausgangspin umwandelt und anschließend den Ausgabemodus festlegt.
  Dadurch entfällt der Laufzeitaufwand für die Überprüfung des aktuellen
  Zustands vor der Ausführung einer Funktion.
] else { todo }

#if lang == "en" [
  Also, because these states are enforced by the type system, there is no
  longer room for errors by consumers of this interface. If they try to
  perform an illegal state transition, the code will not compile!
] else if lang == "de" [
  Da diese Zustände zudem durch das Typsystem erzwungen werden, sind
  Fehler bei der Verwendung dieser Schnittstelle ausgeschlossen. Versucht
  der Nutzer einen unzulässigen Zustandsübergang, lässt sich der Code
  nicht kompilieren!
] else { todo }
